apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akv2k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.spvapi.no
    chart: azure-key-vault-to-kubernetes
    targetRevision: 2.5.3
    helm:
      values: |
        global:
          keyVaultAuth: workloadIdentity
  destination:
    server: https://kubernetes.default.svc
    namespace: akv2k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true