apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: postgres-secret
  namespace: sample-app
spec:
  vault:
    name: kv-k8s-prd-brs-001
  output:
    secret:
      name: postgres-secret
      type: Opaque
  secrets:
    - name: postgres-password
      alias: password